### PR TITLE
update data-viz-alerting version

### PR DESCRIPTION
**Pull request by Jonathan-Eng**
**What is this feature?**

data-viz-alerting version update

### CODE REVIEW

**Review by yasmin-tr — APPROVED** [review]

**Comment by Jonathan-Eng** [comment]
[run-test]

**Comment by Jonathan-Eng** [comment]
[run-test]

**Comment by Jonathan-Eng** [comment]
[run-test]

**Comment by Jonathan-Eng** [comment]
[run-test]

**Comment by npololnskii** [comment]
run-test

**Comment by Jonathan-Eng** [comment]
run-test

**Pull request merged**
