### PR TITLE
DEV-46410 Do not send a notification on error or no data state

### PR DESCRIPTION
**Pull request by yasmin-tr**
**What is this feature?**
Added the following changes:
* Do not send a notification on error or no data state.
* Change default ExecErrState to OK
* Enforce OK state of ExecErrState no matter what value is sent in API calls

**Why do we need this feature?**
What currently is happening in “vanilla” 10:
* Alerts with No Data or Error state will send notification to customer on that state
* User can choose on alert what state to give given NoData/Error - Alerting/NoData/Error/OK/KeepLastState …

**Problems:**
* There is no “mute” time for notifications, so if there is No Data or Error states for an alert, it will continue to notify until issue is resolve, spamming user with a lot of notifications, and cannot be configured by user.
* We don’t want customer to get Error state on alerts, since it is internal issues.

**What we want:**
* Don't send notification on No Data or Error
* Set default error handling state to OK and enforce OK state.

### CODE REVIEW

**Comment by yasmin-tr** [comment]
run-test

**Comment by yasmin-tr** [comment]
run-test

**Comment by yasmin-tr** [comment]
run-test

**Comment by yasmin-tr** [comment]
run-test

**Comment by yasmin-tr** [comment]
run-test

**Review by ohadza — APPROVED** [review]
note - we should think again on comments (of old codes), not blocking

**Comment by yasmin-tr** [comment]
run-test

**Pull request merged**
