### PR TITLE
DEV-45327 - Add Logzio Account Id to alert annotations

### PR DESCRIPTION
**Pull request by yasmin-tr**
**What is this feature?**

For Logzio alert notifications, we add as part of the PostableAlert annotations the LogzioAccountId so we can use it on the notification templates for generating urls to the Logzio app

**Why do we need this feature?**

So url generated in alert notifications can redirect to the relevant account

### CODE REVIEW

**Comment by yasmin-tr** [comment]
run-test

**Review by ohadza — APPROVED** [review]

**Comment by Jonathan-Eng** [comment]
did you verify annotation is indeed sent (test / manually) ?

**Comment by yasmin-tr** [comment]
> did you verify annotation is indeed sent (test / manually) ?

@Jonathan-Eng yes - tested in staging and locally - i see the annotation is added with the account id as expected 🙏

**Comment by Jonathan-Eng** [comment]
💯

**Review by Jonathan-Eng — APPROVED** [review]

**Comment by yasmin-tr** [comment]
run-test

**Comment by npololnskii** [comment]
run-test

**Pull request merged**
