### PR TITLE
DEV-47243 - Handle state cache inconsistency on eval

### PR DESCRIPTION
**Pull request by yasmin-tr**
**What is this feature?**

Added warm to state cache in processTick on schedule, so the state cache will be consistent on evaluations between all running pods.

This is a temporary fix, and does not solve cache-inconsistency issue completely, only makes it less likely to happen. Our long-term solution will need to either support distributed cache in some other way.

Also added the option to config the scheduler interval so we can control more on the cache warmup interval.

**Why do we need this feature?**
To support multiple services running evaluation, i.e. the distributed cache state.

### CODE REVIEW

**Comment by yasmin-tr** [comment]
run-test

**Review by ohadza — COMMENTED** [review]
pls add a comment that is a temporary fix for all this changes (besides the config)

**Comment by yasmin-tr** [comment]
run-test

**Comment by yasmin-tr** [comment]
run-test

**Pull request merged**
